import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Layout: NextPage = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SendOwl bulk update</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>SendOwl bulk update</h1>
        {children}
      </main>

      <footer className={styles.footer}>
        <p className={styles.logo}>
          <span>Made by</span>
          <a
            target="_blank"
            href="https://github.com/pntech20/"
            rel="noreferrer"
          >
            Peter
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Layout;
